mysql:
    image: mysql:5.5
    container_name: mysql
    volumes:
        - $GOPATH/src/github.com/amadeovezz/gobro/db/:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_ROOT_PASSWORD=password
