version: "3"

services:
    mysql:
        image: mysql:5.5
        volumes:
            - $GOPATH/src/github.com/amadeovezz/gobro/db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=password
